[project]
name = "kkbox-churn-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "pyarrow>=25.0.0",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.0",
]

[project.scripts]
kkbox-churn-prediction = "kkbox_churn_prediction:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
